/* eslint-disable prettier/prettier */

 export const CATEGORY = [
        "Rent",
        "Mortgage Payment",
        "Property Taxes",
        "Homeowners Insurance",
        "Home Maintenance/Repairs",
        "HOA Fees",
        "Utility Bills",
        "Internet Service",
        "Cable/Streaming Services",
        "Car Payment",
        "Car Insurance",
        "Fuel/Gas",
        "Public Transportation",
        "Vehicle Maintenance/Repairs",
        "Parking Fees",
        "Ride-Sharing Services",
        "Vehicle Registration",
        "Groceries",
        "Dining Out",
        "Coffee Shops",
        "Snacks",
        "Alcohol",
        "Health Insurance",
        "Medications/Pharmacy",
        "Doctor/Dental Visits",
        "Gym Membership",
        "Haircuts/Beauty Treatments",
        "Skincare/Personal Hygiene Products",
        "Credit Card Payments",
        "Student Loan Payments",
        "Personal Loan Payments",
        "Line of Credit Payments",
        "Movies/Cinema",
        "Concerts/Events",
        "Subscriptions",
        "Hobbies",
        "Books/Magazines",
        "Gaming",
        "Tuition Fees",
        "School Supplies",
        "Books",
        "Online Courses",
        "Educational Subscriptions",
        "Gifts for Family/Friends",
        "Charitable Donations",
        "Church Donations/Tithes",
        "Health Insurance",
        "Life Insurance",
        "Disability Insurance",
        "Renter's Insurance",
        "Pet Insurance",
        "Emergency Fund Contributions",
        "Retirement Contributions",
        "Investment Accounts",
        "College Savings",
        "Daycare/Nanny",
        "School Tuition",
        "Extracurricular Activities",
        "Child Support",
        "Pet Food",
        "Veterinary Bills",
        "Pet Insurance",
        "Grooming",
        "Pet Boarding/Pet Sitting",
        "Clothing",
        "Laundry/Dry Cleaning",
        "Cleaning Supplies",
        "Home Decor",
        "Office Supplies",
        "Postage/Shipping",
        "Legal Fees",
        "Tax Preparation",
        "Airfare",
        "Hotel/Accommodation",
        "Travel Insurance",
        "Car Rental",
        "Dining Out",
        "Sightseeing/Tours",
        "Souvenirs",
        "Travel Gear",
        "Mobile Phone Bill",
        "Landline Phone Bill",
        "Postal Services",
        "Vitamins/Supplements",
        "Mental Health Services",
        "Wellness Programs",
        "Income Tax",
        "Self-Employment Tax",
        "Capital Gains Tax",
        "Office Rent",
        "Software Subscriptions",
        "Advertising/Marketing",
        "Client Entertainment",
        "Travel Expenses",
        "Business Insurance",
        "Water",
        "Electricity",
        "Gas",
        "Trash Removal",
        "Heating Oil"
    ]
